# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e86acae622f95fe88d8f6fb76128f8b8b221c1153f1314d347f742c609dc70be032bde0658191319c00915f084d51a25be5af02d27f31cfb0e0c3321c2b8e1ae

test:
  secret_key_base: 9a2cc9a6756db1ac8d22f603b5a85df86950271d41cdb15bebc94e7fb02700f1fc79a99d57b880397c1bbe2eb60bd8d4582f69de7a9493838dfcdea1f1138b3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
